services:
  db_fisio:
    image: postgres:15-alpine
    container_name: fisio_postgres
    restart: always
    environment:
      POSTGRES_USER: agv_admin
      POSTGRES_PASSWORD: 19Muro96@
      POSTGRES_DB: fisio_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata_fisio:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: fisio_adminer
    restart: always
    ports:
      - "8080:8080"

volumes:
  pgdata_fisio: